FROM microsoft/dotnet:2.1-sdk AS build
COPY /src /src
WORKDIR /src/
RUN dotnet build -o output

FROM microsoft/dotnet:2.1-aspnetcore-runtime AS runtime
COPY --from=build /src/output .
ENTRYPOINT ["dotnet", "MyMvc.dll"]

